pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [mijicd, softinio]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - 'status-success=ci/circleci: test_211_jdk8_jvm'
      - 'status-success=ci/circleci: test_212_jdk8_jvm'
      - 'status-success=ci/circleci: test_212_jdk11_jvm'
      - 'status-success=ci/circleci: test_213_jdk8_jvm'
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: squash
        strict: true
  - name: review PR's by other authors
    conditions:
      - author!=scala-steward
      - 'status-success=ci/circleci: test_211_jdk8_jvm'
      - 'status-success=ci/circleci: test_212_jdk8_jvm'
      - 'status-success=ci/circleci: test_212_jdk11_jvm'
      - 'status-success=ci/circleci: test_213_jdk8_jvm'
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: squash
        strict: true
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
