name: CI

on:
  pull_request:
  push:
    branches: 
      - 'master'
      - 'series/2.x'
  release:
      types:
        - published

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: ./sbt check

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['adopt@1.8', 'adopt@1.11']
        scala: ['2.11.12', '2.12.18', '2.13.11']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: ./sbt ++${{ matrix.scala }}! test

  ci:
    runs-on: ubuntu-22.04
    needs: [lint, test]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"

  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - name: Setup Scala and Java 
        uses: olafurpg/setup-scala@v14
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run:
          ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
